### ISSUE TITLE
CSV is not generated (probably due to spec. characters)

### ISSUE THREAD

**Issue by tcsikos** [halloffame/ynab-csv#5] opened 2014-07-28 07:47 UTC
Hello,
the YNAB csv is not generatd from my original CSV. The reason my be special Hungarian characters in the csv. If I don't set the "payee" field than it exports fine but when 'payee' field is set to the 2nd column it will not download the converted csv. Please find the screenshot (I was not able to attach the csv here)

![image](https://cloud.githubusercontent.com/assets/8287157/3717747/27c84b84-162b-11e4-96cb-0442ddb3f2e0.png)

**Comment by tibu** [comment] 2014-07-30 09:43
Same issue for me. Shall I send over the CSV?

**Comment by halloffame** [comment] 2014-08-06 23:13
@tibu Sure, that would be helpful. You can throw it into a gist and link to it from here.

**Comment by liab** [comment] 2014-08-27 10:52
Hello, First, thanks very much for creating this program, it helps a lot!

I am not able to generate the YNAB csv from Chrome. It worked till 2 days ago, but now is not working anymore. I've tried in another computer, but no luck. What should I do?

**Comment by halloffame** [comment] 2014-08-27 15:46
Thanks @liab. I created a new issue for this, https://github.com/halloffame/ynab-csv/issues/7, so any related discussion can go there. I'll try to take a look at this and the rest of the open issues this weekend.

**Comment by halloffame** [comment] 2014-09-18 06:31
@tcsikos or @tibu can you please provide me with a file with special characters that is giving you problems? You can throw it up on https://gist.github.com/ and reply back with the link to it. Thanks!

**Comment by hamkicker** [comment] 2014-09-20 02:40
I can confirm that the problem is being caused by special characters.  The interesting thing is that if there are special characters in the category headings, the file will export just fine.  Here are my category headings: 年月日,摘要,お支払金額（円）,お預り金額（円）,残高（円）.  That's date, payee, outflow, inflow, and balance.  But if there are special characters anywhere else in the file (like if my payee is 小学校), it won't export.

Unfortunately I couldn't figure out how to make a "gist."  I could email the csv file to you directly if it would help though.

**Comment by ghost** [comment] 2014-10-05 11:40
Faced the same issue. it fails if file contain Cyrilic carachters. Meaning that no error appears, but file doesn't get downloaded. When I remove those symbols - all work well.. But can this be corrected in the program?

**Comment by halloffame** [comment] 2014-10-06 16:11
@spbstolovv Hopefully, I haven't had a chance to look at it yet, but hopefully it is a simple fix. I'll update this thread once it gets fixed.

**Comment by halloffame** [comment] 2014-10-06 16:12
@hamkicker thanks, that should be enough for me to test it out.

**Comment by halloffame** [comment] 2015-02-13 04:41
Sorry it took me so long to get around to this. Should be fixed now though. Turned out to be an easy fix.

**Closed as completed by halloffame** 2015-02-13 04:41 UTC

**Comment by hamkicker** [comment] 2015-02-16 10:47
That's great!  I'm looking forward to trying it out tomorrow.  Thanks for
your hard work!

**Comment by hamkicker** [comment] 2015-02-17 07:04
I just tried it out, and the foreign characters are no longer a problem.
However, the date won't import.  The csv has the format "14.12.28", in
other words "year.month.day" .  Aside from that, the program works great.
Thanks a lot.  Send me your paypal info and I'll buy you a coffee or two!

**Comment by halloffame** [comment] 2015-02-17 22:39
Thanks. Yeah, there is another issue open for adding better date support https://github.com/halloffame/ynab-csv/issues/9
